### ISSUE TITLE
init 生成失败，提示Template simple not found.

### ISSUE THREAD

**Issue by xqbumu** [yodaos-project/yoda-platform-tools#5]
Version: v0.0.12
Platform: macOS 10.14.2 
Subsystem: nvm v0.33.11, node v11.1.0, npm v6.4.1

```sh
⇒  yoda-cli init app demo
✖  error     Error: Template simple not found.
```

问题临时解决方法：
复制
https://github.com/yodaos-project/yoda-platform-tools/tree/master/yoda-cli/boilerplates
到 yoda-cli 位置的父目录相对 lib/node_modules/yoda-cli 的目录中。

**Comment by xqbumu** [comment]
还有，

执行：
```
yoda-cli pm install demo
```

返回：
```
FailError: Failure: 'secure_mkdirs failed: Read-only file system'
    at .../node_modules/adbkit/lib/adb/sync.js:289:33
    at tryCatcher (.../node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (.../node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (.../node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (.../node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (.../node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (.../node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (.../node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate (timers.js:632:19)
```

**Comment by legendecas** [comment]
`FailError: Failure: 'secure_mkdirs failed: Read-only file system'` is caused by read only file system on target device. Devices with production version image burnt are read-only on non-`/data` partitions.

生产版的机器只有 /data 目录是可写的，默认是安装到 /opt/apps 下，所以会有 `secure_mkdirs failed: Read-only file system`

**Comment by xqbumu** [comment]
@legendecas yoda-cli 还没细看，所以应该有个可以选择或指定安装位置的扩展选项。（手动滑稽）

**Comment by legendecas** [comment]
Cannot re-produce with a fresh download from https://github.com/yodaos-project/yoda-platform-tools/releases/tag/v0.0.12 in a fresh clean directory. May I know how do you get the command line tool and what's in the directory of the tool?

**Comment by legendecas** [comment]
> @legendecas yoda-cli 还没细看，所以应该有个可以选择或指定安装位置的扩展选项。（手动滑稽）

The options is available now through vscode settings. Declarations https://github.com/yodaos-project/yoda-platform-tools/blob/v0.0.12/yoda-vscode/package.json#L43 .

**Comment by xqbumu** [comment]
通过
```
npm install -g yoda-cli
```
之后的安装目录在：
./nvm/versions/node/v11.1.0/lib/node_modules/yoda-cli

```
⇒  tree -L 1
.
├── LICENSE.md
├── README.md
├── bin
├── node_modules
├── out
├── package-lock.json
├── package.json
├── src
├── tsconfig.json
└── yarn.lock
```

其实是通过 npm 安装后，缺少 boilerplates 这个目录，当我手动下载添加这个目录及文件后，可以正常使用。

**Comment by legendecas** [comment]
Resolved by 1696ae984511d88fdaaf7c132ec234d8334bdd2c
